import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 11,
    lineHeight: 1.5,
    color: "#1E293B",
  },
  header: {
    borderBottomWidth: 2,
    borderBottomColor: "#0B6E6E",
    paddingBottom: 8,
    marginBottom: 16,
  },
  facilityName: {
    fontSize: 18,
    fontWeight: 700,
    color: "#0D2B4E",
    marginBottom: 2,
  },
  metaRow: {
    fontSize: 10,
    color: "#4B5E73",
    flexDirection: "row",
    gap: 4,
  },
  section: {
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "#0B6E6E",
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    paddingBottom: 4,
    marginBottom: 8,
  },
  paragraph: {
    marginBottom: 4,
  },
  translationSection: {
    marginTop: 20,
    borderTopWidth: 2,
    borderTopColor: "#0D2B4E",
    paddingTop: 14,
  },
  lowConfidenceNote: {
    marginTop: 8,
    fontStyle: "italic",
    color: "#B45309",
    fontSize: 10,
  },
  fallbackNote: {
    fontStyle: "italic",
    color: "#4B5E73",
    fontSize: 10,
  },
  footer: {
    marginTop: 24,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    fontSize: 9,
    color: "#4B5E73",
  },
});

interface ExportData {
  facilityName: string;
  patientName: string;
  dischargeDate: string;
  clinicianName: string;
  clinicalSummary: string;
  patientFriendlyOutput: string;
  translatedOutput?: string | null;
  translationLanguage?: string | null;
  translationConfidence?: string | null;
}

const languageLabel: Record<string, string> = {
  ha: "Hausa",
  yo: "Yoruba",
  ig: "Igbo",
};

function stripSeparators(text: string): string {
  return text.replace(/─{2,}/g, "").trim();
}

interface DischargePdfProps {
  data: ExportData;
}

export async function renderDischargePdfToBuffer(data: ExportData): Promise<Buffer> {
  return renderToBuffer(<DischargePdf data={data} />);
}

export function DischargePdf({ data }: DischargePdfProps) {
  const bodyLines = stripSeparators(data.patientFriendlyOutput)
    .split("\n")
    .filter((l) => l.trim());

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.facilityName}>{data.facilityName}</Text>
          <View style={styles.metaRow}>
            <Text>Patient: {data.patientName}</Text>
            <Text> | </Text>
            <Text>Discharge date: {data.dischargeDate}</Text>
            <Text> | </Text>
            <Text>Clinician: {data.clinicianName}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Discharge Instructions</Text>
          {bodyLines.map((line, i) => (
            <Text key={i} style={styles.paragraph}>{line}</Text>
          ))}
        </View>

        {data.translatedOutput && data.translationLanguage ? (
          <View style={styles.translationSection}>
            <Text style={styles.sectionTitle}>
              {languageLabel[data.translationLanguage] ?? data.translationLanguage} Translation
            </Text>
            {stripSeparators(data.translatedOutput)
              .split("\n")
              .filter((l) => l.trim())
              .map((line, i) => (
                <Text key={i} style={styles.paragraph}>{line}</Text>
              ))}
            {data.translationConfidence === "low" && (
              <Text style={styles.lowConfidenceNote}>
                Note: This translation was completed with low confidence. Please verify with a fluent speaker.
              </Text>
            )}
          </View>
        ) : data.translatedOutput && (
          <View style={styles.translationSection}>
            <Text style={styles.fallbackNote}>
              Translation into {data.translationLanguage ?? "the requested language"} could not be completed
              with sufficient confidence. English version is shown above.
            </Text>
          </View>
        )}

        <Text style={styles.footer}>
          Generated by Lafiyanku. This is a computer-generated document. Always verify with your clinician.
        </Text>
      </Page>
    </Document>
  );
}
