"use client";

import { Button } from "@/components/ui/button";
import { Printer } from "lucide-react";
import { toast } from "sonner";

interface PrintButtonProps {
  patientName: string;
  facilityName: string;
  dischargeDate: string;
  clinicianName: string;
  patientFriendlyOutput: string;
  translatedOutput?: string | null;
  translationLanguage?: string | null;
  translationConfidence?: string | null;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function stripSeparators(text: string): string {
  return text.replace(/─{2,}/g, "").trim();
}

const languageLabel: Record<string, string> = {
  ha: "Hausa",
  yo: "Yoruba",
  ig: "Igbo",
};

export function PrintButton({
  patientName,
  facilityName,
  dischargeDate,
  clinicianName,
  patientFriendlyOutput,
  translatedOutput,
  translationLanguage,
  translationConfidence,
}: PrintButtonProps) {
  function handlePrint() {
    const showTranslation =
      translatedOutput &&
      translationLanguage &&
      (translationConfidence === "high" || translationConfidence === "low");

    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      toast.error("Popup blocked. Please allow popups for this site and try again.");
      return;
    }

    const safePatientName = escapeHtml(patientName);
    const safeFacilityName = escapeHtml(facilityName);
    const safeDischargeDate = escapeHtml(dischargeDate);
    const safeClinicianName = escapeHtml(clinicianName);
    const safeOutput = escapeHtml(stripSeparators(patientFriendlyOutput));
    const safeTranslation = translatedOutput ? escapeHtml(stripSeparators(translatedOutput)) : "";
    const safeLangLabel = translationLanguage ? escapeHtml(languageLabel[translationLanguage!] ?? translationLanguage) : "";

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Discharge Instructions - ${safePatientName}</title>
        <meta charset="utf-8">
        <style>
          @page { margin: 20mm 15mm; }
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body {
            font-family: 'Segoe UI', Arial, sans-serif;
            font-size: 12pt;
            line-height: 1.6;
            color: #1E293B;
            max-width: 210mm;
            margin: 0 auto;
            padding: 20mm 15mm;
          }
          .header {
            border-bottom: 2px solid #0B6E6E;
            padding-bottom: 8pt;
            margin-bottom: 16pt;
          }
          .header h1 { font-size: 18pt; color: #0D2B4E; margin-bottom: 2pt; }
          .header p { font-size: 10pt; color: #4B5E73; }
          .section { margin-bottom: 14pt; }
          .section h2 {
            font-size: 14pt;
            color: #0B6E6E;
            border-bottom: 1px solid #E2E8F0;
            padding-bottom: 4pt;
            margin-bottom: 8pt;
          }
          .section p { margin-bottom: 4pt; }
          .footer {
            margin-top: 24pt;
            padding-top: 8pt;
            border-top: 1px solid #E2E8F0;
            font-size: 9pt;
            color: #4B5E73;
          }
          @media print {
            body { padding: 0; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${safeFacilityName}</h1>
          <p>Patient: ${safePatientName} | Discharge date: ${safeDischargeDate} | Clinician: ${safeClinicianName}</p>
        </div>

        <div class="section">
          <h2>Discharge Instructions</h2>
          ${safeOutput.split("\n").map((line) => (line.trim() ? `<p>${line}</p>` : "")).join("")}
        </div>

        ${
          showTranslation
            ? `
        <div class="section" style="margin-top: 20pt; border-top: 2px solid #0D2B4E; padding-top: 14pt;">
          <h2>${safeLangLabel} Translation</h2>
          ${safeTranslation.split("\n").map((line) => (line.trim() ? `<p>${line}</p>` : "")).join("")}
          ${
            translationConfidence === "low"
              ? '<p style="margin-top: 8pt; font-style: italic; color: #B45309;">Note: This translation was completed with low confidence. Please verify with a fluent speaker.</p>'
              : ""
          }
        </div>`
            : translatedOutput && translationConfidence === "failed"
              ? `
        <div class="section" style="margin-top: 20pt; border-top: 2px solid #0D2B4E; padding-top: 14pt;">
          <p style="font-style: italic; color: #4B5E73;">Translation into ${safeLangLabel} could not be completed with sufficient confidence. English version is shown above.</p>
        </div>`
              : ""
        }

        <div class="footer">
          <p>Generated by Lafiyanku. This is a computer-generated document. Always verify with your clinician.</p>
        </div>
      </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 300);
  }

  return (
    <Button
      variant="outline"
      size="sm"
      className="touch-target-min"
      onClick={handlePrint}
    >
      <Printer className="mr-1 h-4 w-4" />
      Print
    </Button>
  );
}
